filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /var/log/kibana/kibana.log
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
setup.kibana:
  host: "localhost:5601"
  username: "elastic"
  password: "${ES_PWD}"
output.elasticsearch:
  hosts: ["localhost:9200"]
  username: "elastic"
  password: "${ES_PWD}"
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~